menu:
  koalamon_project_admin:
    notification_main:
      label: Notifications
      options:
        route: koalamon_notification_home
        routeParameters:
          project: @route

    notification_sub_channels:
      parent: notification_main
      label: Channels
      options:
        route: koalamon_notification_home
        routeParameters:
          project: @route

    notification_sub_alerts:
      parent: notification_main
      label: Alerts
      options:
        route: koalamon_notification_alerts_home
        routeParameters:
          project: @route