services:

    koalamonnotification.eventCreationListener:
        class: Koalamon\NotificationBundle\EventListener\EventListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.event.create', method: onEventCreate }