services:
  koalamonnotification.eventlistener:
    class: Koalamon\NotificationBundle\EventListener\EventListener
    arguments: [ @service_container ]
    tags:
      - { name: koalamon.event_listener, event: koalamon.notification.event.create, method: onEventCreate }